### PR TITLE
Properly escape quote characters in Localizable.strings files

### LINKED ISSUE #33: Quotes are not properly escaped on iOS
## Steps to reproduce
Given the following Localicipe:
```
IOS:
  Module:
    Screen:
      Element:
        COPY:
          en: "This is a <a href=\"https://github.com/PicnicSupermarket/localicious\">link</a>"
```
## Observed behaviour
Localicious generates the following Localizable.strings file:
```
"Module.Screen.Element.COPY" = "This is a <a href="https://github.com/PicnicSupermarket/localicious">link</a>";
```

This leads to the following error in Xcode: `Localizable.strings:1:1: read failed: Couldn't parse property list because the input data was in an invalid format`

## Expected behaviour
Running `plutil` leads us to the culprit:

```
2020-05-28 13:51:12.415 plutil[35933:1269394] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 1. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
Localizable.strings: Unexpected character " at line 1
```

From this, we can conclude that the following Localizable.strings file is expected by Xcode:

```
"Module.Screen.Element.COPY" = "This is a <a href=\"https://github.com/PicnicSupermarket/localicious\">link</a>";
```

### PR DESCRIPTION
**Pull request by larslockefeer**
Fixes #33

### CODE REVIEW

File: src/actions/render.js [hunk 1]
```diff
@@ -140,7 +140,7 @@ const substitutionsForPlatform = platform => {
         { search: percentEncodingPattern, replace: "%%" },
         { search: "{{s}}", replace: "$@" },
         { search: "{{d}}", replace: "$d" },
-        { search: "\"", replace: "\\\"" }
+        { search: '"', replace: '\\"' }
```
Comment (larslockefeer) [inline src/actions/render.js:143]: @LcTwisk This is what prettier suggest. I'm not sure what to think of it?

Comment (LcTwisk) [reply src/actions/render.js:143]: Would prefer consistent quotes but I can live with this ;)
